# Generated by Django 2.1.3 on 2018-11-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datatypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=300)),
                ('field_value', models.CharField(blank=True, max_length=200, null=True)),
                ('field_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='datatypes',
            name='risk_rel',
            field=models.ForeignKey(on_delete=True, related_name='datatypes', to='britecore.Risk'),
        ),
    ]
